name: Cache and Install
description: Cache pnpm store and install dependencies

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
      with:
        node-version: '22.x'
        check-latest: true
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
