# Ref: PlaywrightのブラウザバイナリをGitHub Actionsでキャッシュする
# https://qiita.com/ohakutsu/items/8e4c10cad360bf4cda04
name: Setup Playwright
description: Setup Playwright

inputs:
  playwright-browsers-path:
    description: playwright browsers path
    required: true

runs:
  using: composite
  steps:
    - run: echo "PLAYWRIGHT_VERSION=$(node -e 'console.log(require("playwright/package.json").version)')" >> "${GITHUB_ENV}"
      shell: bash

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      id: cache-playwright-browsers
      with:
        path: ${{ inputs.playwright-browsers-path }}
        key: |
          ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-

    - run: pnpm playwright install --with-deps
      if: ${{ steps.cache-playwright-browsers.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        PLAYWRIGHT_BROWSERS_PATH: ${{ inputs.playwright-browsers-path }}
